
import {
    Task, TaskGroup, WorkspaceFolder, ShellExecution, Uri, workspace, ShellExecutionOptions, extensions
} from "vscode";
import * as path from "path";
import * as util from "../common/utils";
import * as log from "../common/log";
import { configuration } from "../common/configuration";
import { filesCache } from "../cache";
import { TaskExplorerProvider } from "./provider";
import { TaskExplorerDefinition } from "../taskDefinition";


// Find likely target rules in a Makefile and supply them to Task Explorer as task names.
//
// Notes: 
//  * Rules contain alphanumeric characters plus _, -, /, period (.), or spaces (' ') 
//    (for multiple targets generated by a rule)
//  * Targets using patterns, wildcards or environment variables are omitted
//    (since these cannot be used directly as literal targets) 
//      * these use characters like %, $, *, ? which are not included in the search
//         patern.
//  * Rules starting with . (special targets) are omitted 
//  * Whitespace between rule and : is allowed
//  * Whitespace between start of line and rule name is not allowed.
//  * Repeated rules are allowed, the set of unique rule names are used to create Tasks, 
//    we just let Make deal with multiple rules (which depends on how they were defined: overridden, 
//    double-colon, conditionally, etc.)
//  * "include" directives are not followed.
//  * No variable expansion in performed.  Conditional sections are not
//    evaluated, any rules in any branch of a conditional will be found.  We are
//    just looking for rule patterns in the file text.

export class MakeTaskProvider extends TaskExplorerProvider implements TaskExplorerProvider
{

    private ruleTargetExp = /^([\w-.\/ ]+)\s*:[^=]/mg;  // note does not disallow leading '.', this must be checked separately.


    constructor() { super("make"); }


    public createTask(target: string, cmd: string, folder: WorkspaceFolder, uri: Uri, xArgs?: string[], logPad = ""): Task
    {
        log.methodStart("create make task", 4, logPad, true);

        const getCommand = (): string =>
        {
            let make = "make";
            if (process.platform === "win32") {
                make = "nmake";
            }
            if (configuration.get("pathToMake")) {
                make = configuration.get("pathToMake");
                //
                // Ref ticket #138 - temp logging
                //
                log.value("   set make program from settings", make, 5, logPad);
            }
            log.value("   make program", make, 5, logPad);
            return make;
        };

        const kind = this.getDefaultDefinition(target, folder, uri);

        const cwd = path.dirname(uri.fsPath);
        const args = [target];
        const options: ShellExecutionOptions = {
            cwd
        };

        const execution = new ShellExecution(getCommand(), args, options);
        let problemMatcher = "$gccte";
        const cPlusPlusExtension = extensions.getExtension("spmeesseman.vscode-taskexplorer");
        if (cPlusPlusExtension) {
            problemMatcher = "$gcc";
        }

        log.methodDone("create make task", 4, logPad, true);

        return new Task(kind, folder, target, "make", execution, problemMatcher);
    }


    public getDocumentPosition(taskName: string | undefined, documentText: string | undefined): number
    {
        if (!taskName || !documentText) {
            return 0;
        }
        let idx = documentText.indexOf(taskName + ":");
        if (idx === -1)
        {
            idx = documentText.indexOf(taskName);
            let bLine = documentText.lastIndexOf("\n", idx) + 1;
            let eLine = documentText.indexOf("\n", idx);
            if (eLine === -1) { eLine = documentText.length; }
            let line = documentText.substring(bLine, eLine).trim();
            while (bLine !== -1 && bLine !== idx && idx !== -1 && line.indexOf(":") === -1)
            {
                idx = documentText.indexOf(taskName, idx + 1);
                bLine = documentText.lastIndexOf("\n", idx) + 1;
                eLine = documentText.indexOf("\n", idx);
                if (bLine !== -1)
                {
                    if (eLine === -1) { eLine = documentText.length; }
                    line = documentText.substring(bLine, eLine).trim();
                }
            }
        }
        return idx;
    }

/*     // Return matching rules from the Makefile with file name fsPath. 
    // The result of String matchAll() is returned, an iterator.
    private getMakefileRules(fsPath: string)
    {
        const contents = util.readFileSync(fsPath);
        return contents.matchAll(this.ruleTargetExp); // matchAll() Added to chrome in version 73.
    } */

    private findTargets(fsPath: string, logPad = ""): string[]
    {
        const scripts: string[] = [];

        log.blank(1);
        log.write(logPad + "find makefile targets");
    

        //const rules = this.getMakefileRules(fsPath);
        //for (const r of rules)
        //{... }


        //console.log(`Task Explorer: searching Makefile '${fsPath}' for targets...`);
        const contents = util.readFileSync(fsPath);
        let match = null;
        while((match = this.ruleTargetExp.exec(contents)) != null)
        {
            const rule = match[1];
            if (rule.startsWith('.')) // skip special targets
                continue;
            //console.log(`Task Explorer: found rule name: '${match[1]}'`);
            if (!scripts.includes(rule)) // avoid duplicates
                scripts.push(rule);
        }

        log.write(logPad + "find makefile targets complete", 1);

        return scripts;
    }


    public getDefaultDefinition(target: string, folder: WorkspaceFolder, uri: Uri): TaskExplorerDefinition
    {
        const def: TaskExplorerDefinition = {
            type: "make",
            script: target,
            target,
            path: util.getRelativePath(folder, uri),
            fileName: path.basename(uri.path),
            problemMatcher: "",
            uri
        };
        return def;
    }

    public async readTasks(logPad = ""): Promise<Task[]>
    {
        log.methodStart("detect make files", 1, logPad, true);

        const allTasks: Task[] = [];
        const visitedFiles: Set<string> = new Set();
        const paths = filesCache.get("make");

        if (workspace.workspaceFolders && paths)
        {
            for (const fobj of paths)
            {
                if (!util.isExcluded(fobj.uri.path) && !visitedFiles.has(fobj.uri.fsPath))
                {
                    visitedFiles.add(fobj.uri.fsPath);
                    const tasks = await this.readUriTasks(fobj.uri, undefined, logPad + "   ");
                    log.write("   processed make file", 3, logPad);
                    log.value("      file", fobj.uri.fsPath, 3, logPad);
                    log.value("      targets in file", tasks.length, 3, logPad);
                    allTasks.push(...tasks);
                }
            }
        }

        log.blank();
        log.value("   # of make tasks", allTasks.length, 2, logPad);
        log.methodDone("detect make files", 1, logPad, true);

        return allTasks;
    }


    public async readUriTasks(uri: Uri, wsFolder?: WorkspaceFolder, logPad = ""): Promise<Task[]>
    {
        const result: Task[] = [];
        const folder = wsFolder || workspace.getWorkspaceFolder(uri);

        log.methodStart("read make file uri tasks", 1, logPad, true, [["path", uri?.fsPath], ["project folder", folder?.name]]);

        if (folder)
        {
            const scripts = this.findTargets(uri.fsPath, logPad + "   ");
            if (scripts)
            {
                for (const s of scripts)
                {
                    const task = this.createTask(s, s, folder, uri, undefined, logPad);
                    task.group = TaskGroup.Build;
                    result.push(task);
                }
            }
        }

        log.methodDone("read make file uri tasks", 1, logPad);
        return result;
    }

}
